# Copyright 2018 WSO2, Inc. (http://wso2.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License

---
servers:
  -
    hostname: wso2-mysql
    box: wso2-mysql
    ip: 172.28.128.3
    ram: 2048
    cpu: 1
    provisioner_script: mysql/provisioner/db_provisioner.sh
    conf_dir: mysql/scripts
  -
    hostname: analytics-worker
    box: wso2ei
    ip: 172.28.128.4
    ram: 2048
    cpu: 1
    provisioner_script: analytics-worker/provisioner/product_provisioner.sh
    conf_dir: analytics-worker
  -
    hostname: analytics-dashboard
    box: wso2ei
    ip: 172.28.128.6
    ports:
      - 9643
    ram: 2048
    cpu: 1
    provisioner_script: analytics-dashboard/provisioner/product_provisioner.sh
    conf_dir: analytics-dashboard
  -
    hostname: broker
    box: wso2ei
    ip: 172.28.128.5
    ports:
      - 9446
    ram: 2048
    cpu: 1
    provisioner_script: broker/provisioner/product_provisioner.sh
    conf_dir: broker
  -
    hostname: integrator
    box: wso2ei
    ip: 172.28.128.7
    ports:
      - 9443
    ram: 2048
    cpu: 1
    provisioner_script: integrator/provisioner/product_provisioner.sh
    conf_dir: integrator
